(defun color-theme-easy-python ()
  (interactive)
  (color-theme-install
   '(color-theme-easy-python
      ((background-color . "#283039")
      (background-mode . light)
      (border-color . "#000000")
      (cursor-color . "#ff1a1e")
      (foreground-color . "#ffffff")
      (mouse-color . "black"))
     (fringe ((t (:background "#000000"))))
     (mode-line ((t (:foreground "#000000" :background "#374948"))))
     (region ((t (:background "#4e564f"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#92a97e"))))
     (font-lock-function-name-face ((t (:foreground "#c5777b"))))
     (font-lock-keyword-face ((t (:foreground "#b9d4e4"))))
     (font-lock-string-face ((t (:foreground "#68c22e"))))
     (font-lock-type-face ((t (:foreground"#d9bad8"))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide  'color-theme-easy-python)