#!/usr/bin/bash

dzen2 -p 0 -dock -w 1600 &
sleep 1
$HOME/.config/wingo/scripts/jenkins &
sleep 1
$HOME/.config/wingo/scripts/battery &
sleep 1
$HOME/.config/wingo/scripts/dzenbar &
sleep 1
$HOME/.config/wingo/scripts/clockbar
