;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cljr-slash
        forward-sexp
        indent-for-tab-command
        kill-region
        slime-space
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        cljr-move-to-let
        ))
