;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        asm-colon
        c-indent-line-or-region
        cljr-slash
        erlang-electric-comma
        erlang-electric-gt
        forward-sexp
        indent-for-tab-command
        kill-region
        mark-sexp
        slime-autodoc-space
        slime-space
        smex
        typescript-insert-and-autoconvert-to-template
        typescript-insert-and-indent
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-semi&comma
        cljr-move-to-let
        markdown-exdent-or-delete
        ))
